FROM amazon/aws-lambda-nodejs:14
RUN mkdir /tmp/build/
COPY . /tmp/build/
RUN echo $(ls /tmp/build)
RUN echo $(ls /tmp/build)
COPY /layers/layer-core-executor/ /opt
WORKDIR /opt/nodejs
RUN npm install
COPY /layers/layer-framework-scraping/ /opt
WORKDIR /opt/nodejs
RUN npm install
RUN mkdir -p /opt/disable-extensions-jwigqn8j
EXPOSE 8080
CMD ["/opt/nodejs/executor.handler"]