version: "3.9"  # optional since v1.27.0
services:

  redis:
    container_name: "h0ck-redis"
    image: "bitnami/redis:latest"
    ports: 
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes